name: Unit test workflow (on-commit)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4         # Specify version for best practices

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3  # Specify version here as well
        with:
          auto-update-conda: true
          python-version: '3.10'
          activate-environment: mlxc
          use-only-tar-bz2: true

      - name: Set environment
        run: |
          conda init bash
          export CXX11_ABI_FLAG=1

      - name: Install dependencies - PyTorch (CPU)
        run: |
          conda activate mlxc
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

      - name: Install dependencies - DeePMD-kit
        run: |
          conda activate mlxc
          pip install git+https://github.com/deepmodeling/deepmd-kit@v3.1.0a0
      
      - name: Install dependencies - DPData
        run: |
          conda activate mlxc
          pip install dpdata

      - name: Install dependencies - Huggingface
        run: |
          conda activate mlxc
          pip install huggingface_hub

      - name: Install dependencies - UniMol
        run: |
          conda activate mlxc
          pip install unimol_tools --upgrade

      - name: Install the package
        run: |
          conda activate mlxc
          pip install .

      - name: Set up permissions for execute
        run: chmod +x ./.github/scripts/ut_driver.sh

      - name: Run unit test driver to execute all unit test registered
        run: |
          conda activate mlxc
          output=$(./.github/scripts/ut_driver.sh)
          exit_code=$?
          echo "$output"
          if [ $exit_code -ne 0 ]; then
            echo "Tests failed with exit code $exit_code"
            exit $exit_code
          fi